# Full reference: https://docs.airplane.dev/tasks/task-definition

slug: demo_search_customers
name: Search customers
description: "SQL task that shows all customers that match a search keyword."
parameters:
  - slug: search_keyword
    name: Search keyword
    type: shorttext
    description: The search string
    required: false
sql:
  # Replace with your own DB name
  resource: "demo_db"
  entrypoint: search_customers.sql
  queryArgs:
    keyword: "{{params.search_keyword}}"
