# Full reference: https://docs.airplane.dev/tasks/task-definition

slug: demo_update_ship_address
name: Update ship address for order
description: "SQL task that updates a contact name for a customer."
parameters:
  - slug: order_id
    name: Order ID
    type: integer
    required: true
  - slug: ship_address
    name: New ship address
    type: shorttext
    required: true
sql:
  # Replace with your own DB name
  resource: "demo_db"
  entrypoint: update_ship_address.sql
  queryArgs:
    order_id: "{{params.order_id}}"
    ship_address: "{{params.ship_address}}"
